repos:
- repo: local
  hooks:
  - id: lint-check-test
    name: Checking source files and running tests
    entry: "./pants lint check test ::"
    language: script
    types: [python]
    pass_filenames: false
    verbose: true
  - id: lint-build-files
    name: Checking BUILD files
    entry: "./pants --no-pantsd update-build-files --check"
    language: script
    files: BUILD
    pass_filenames: false
    verbose: true
